version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: circle3space-web
    ports:
      - "5001:5001"
    volumes:
      - ./media:/app/wwwroot/media
    restart: always
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: Production

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: circle3space-sql
    environment:
      SA_PASSWORD: "P@ssw0rd123Circle"
      ACCEPT_EULA: "Y"
    volumes:
      - /var/opt/mssql/data:/var/opt/mssql/data
      - /var/opt/mssql/backups:/var/opt/mssql/backups
    ports:
      - "1434:1433"
    restart: always
