version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: circle3space-sql
    environment:
      SA_PASSWORD: "P@ssw0rd123Circle"
      ACCEPT_EULA: "Y"
    ports:
      - "1544:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  web:
    build: .
    container_name: circle3space-web
    ports:
      - "5055:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "circle3coworkingspace.dll"]



volumes:
  sqlserverdata:
