version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: circle3space-sql
    environment:
      SA_PASSWORD: "P@ssw0rd123Circle"
      ACCEPT_EULA: "Y"
    ports:
      - "1544:1433"
    restart: always
    volumes:
      - sqlserverdata:/var/opt/mssql

  web:
    build:
      context: .
    container_name: circle3space-web
    ports:
      - "5055:44370"
    environment:
      - ConnectionStrings__umbracoDbDSN=Server=circle3space-sql,1433;Database=c3space;User Id=SA;Password=P@ssw0rd123Circle;TrustServerCertificate=True;
    restart: always
    depends_on:
      - sqlserver
    volumes:
      - ./media:/app/wwwroot/media

volumes:
  sqlserverdata:
